function []=input_list_check(myFunction,myNargin);
%object:	print warning/error messages related to 
%		changes in arguments lists (June 2011).
%inputs:	myFunction: name of the calling routine
%		myNargin: number of arguments passed to the calling routine

if strcmp(myFunction,'convert2gcmfaces')&myNargin~=1;
    warning('inputCheck:convert2gcmfaces',...
            ['As of june 2011, convert2gcmfaces.m expects only \n' ...
    '         one input argument. The others were dismissed.\n' ...
    '         Type ''help convert2gcmfaces'' for details.']);
end;

if strcmp(myFunction,'convert2array')&myNargin~=1;
    warning('inputCheck:convert2array',...
            ['As of june 2011, convert2array.m expects only \n' ...
    '         one input argument. The other ones are dismissed.\n' ...
    '         Type ''help convert2array'' for details.']);
end;

if strcmp(myFunction,'convert2pcol')&myNargin~=3;
    warning('inputCheck:convert2pcol',...
            ['As of june 2011, convert2pcol.m expects only \n' ...
    '         three input arguments. The other ones are dismissed.\n' ...
    '         Type ''help convert2pcol'' for details.']);
end;

if strcmp(myFunction,'grid_load')&(myNargin~=3&myNargin~=4);
    error('inputCheck:grid_load',...
    ['As of Sept 2012, grid_load.m is a \n' ...
     'function with three or four input arguments. \n'...
     'Type ''help grid_load'' for details.\n']);
end;

if strcmp(myFunction,'plot_one_field')&myNargin~=2;
    error('inputCheck:plot_one_field',...
    ['As of june 2011, plot_one_field.m is a \n' ...
     'function with two input argument. \n'...
     'Type ''help plot_one_field'' for details.\n']);
end;

if strcmp(myFunction,'plot_std_field')&myNargin~=1;
    error('inputCheck:plot_std_field',...
    ['As of june 2011, plot_std_field.m is a \n' ...
     'function with one input argument. \n'...
     'Type ''help plot_std_field'' for details.\n']);
end;

if strcmp(myFunction,'basic_diags_compute_v3_or_v4')&myNargin~=1;
    error('inputCheck:basic_diags_compute_v3_or_v4',...
    ['As of june 2011, basic_diags_compute_v3_or_v4.m is a \n' ...
     'function with one input argument. \n'...
     'Type ''help basic_diags_compute_v3_or_v4'' for details.\n']);
end;

if strcmp(myFunction,'basic_diags_display_v3_or_v4')&myNargin~=1;
    error('inputCheck:basic_diags_display_v3_or_v4',...
    ['As of june 2011, basic_diags_display_v3_or_v4.m is a \n' ...
     'function with one input argument. \n'...
     'Type ''help basic_diags_display_v3_or_v4'' for details.\n']);
end;

